import './modules/aside.js'
import './modules/last-update.js'
import './modules/theme-toggle.js'
import './modules/articles-gallery.js'
import './modules/persons-list.js'
import './modules/article-nav.js'
import './modules/header.js'
